const router = require('express').Router(); const rateLimit = require('express-rate-limit'); const multer = require('multer'); const auth = require('../controllers/auth.controller'); const products = require('../controllers/products.controller'); const blogs = require('../controllers/blogs.controller'); const uploads = require('../controllers/uploads.controller'); const { requireAdmin, requireCsrf } = require('../middleware/auth');
const loginLimit = rateLimit({ windowMs: 15 * 60 * 1000, max: 8, standardHeaders: true, legacyHeaders: false, message: { success: false, message: 'Too many login attempts. Try again later.' } });
const writeLimit = rateLimit({ windowMs: 60 * 1000, max: 60, standardHeaders: true, legacyHeaders: false });
const imageUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 8 * 1024 * 1024, files: 1 }, fileFilter: (_req, file, callback) => callback(null, /^image\/(jpeg|png|webp|gif|avif)$/i.test(file.mimetype)) });
router.get('/setup-status', auth.setupStatus); router.post('/bootstrap', loginLimit, auth.bootstrap); router.post('/login', loginLimit, auth.login); router.get('/me', requireAdmin, auth.me); router.post('/logout', requireAdmin, requireCsrf, auth.logout);
router.get('/products', requireAdmin, products.listAdmin); router.post('/products', requireAdmin, requireCsrf, writeLimit, products.create); router.put('/products/:id', requireAdmin, requireCsrf, writeLimit, products.update); router.post('/products/:id/duplicate', requireAdmin, requireCsrf, writeLimit, products.duplicate); router.post('/products/:id/status', requireAdmin, requireCsrf, writeLimit, products.setStatus); router.delete('/products/:id', requireAdmin, requireCsrf, writeLimit, products.archive);
router.post('/uploads/images', requireAdmin, requireCsrf, writeLimit, imageUpload.single('file'), uploads.uploadImage);
router.get('/blogs', requireAdmin, blogs.listAdmin); router.post('/blogs', requireAdmin, requireCsrf, writeLimit, blogs.create); router.put('/blogs/:id', requireAdmin, requireCsrf, writeLimit, blogs.update); router.post('/blogs/:id/duplicate', requireAdmin, requireCsrf, writeLimit, blogs.duplicate); router.post('/blogs/:id/status', requireAdmin, requireCsrf, writeLimit, blogs.setStatus); router.delete('/blogs/:id', requireAdmin, requireCsrf, writeLimit, blogs.archive);
module.exports = router;
